--FOREIGN KEY - CHAVE ESTRANGEIRA - FK

--É A CHAVE PRIMARIA DE UMA TABELA, QUE VAI ATE OUTRA TABELA FAZER REFERENCIA.

--EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA.

--EM RELACIONAMENTOS 1 X N, A CHAVEE ESTRANGEIRA FICARA SEMPRE NA TABELA N.