CREATE TABLE CLIENTE(
   IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR(30) NOT NULL,
   SEXO ENUM('M', 'F') NOT NULL,
   EMAIL VARCHAR(50) UNIQUE,
   CPF VARCHAR(15) UNIQUE
);

--Inserção na tabela
INSERT INTO CLIENTE VALUES (NULL, 'Joao', 'M', 'joao@gmail.com', '98547-6');
INSERT INTO CLIENTE VALUES(NULL,'Carlos','M','carlos@tera.com','86664-7');
INSERT INTO CLIENTE VALUES(NULL,'Ana','F','ana@globo.com','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'Jorge','M','jorge@ig.com','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'Clara','M',NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'Celia','F','joao@terra.com','77558-5');

