--PROJECAO - TUDO QUE QUEREMOS PROJETAR NA TELA
SELECT NOW() AS "DATA";

--JUNCAO
SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS "DATA" 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE;


SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS "DATA" 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE
AND BAIRRO = 'CENTRO';


--JOIN - JUNCAO
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE 
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE BAIRRO = 'CENTRO';


--Queries - SELECAO - PROJECAO E JUNCAO
--PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
--RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
--DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
--VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
--O PROGRAMADOR
SELECT C.NOME, C.EMAIL, T.NUMERO 
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE 
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';

--PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
--RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
-- DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
--VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
--O PROGRAMADOR
SELECT NOME, EMAIL, NUMERO
FROM CLIENTE 
INNER JOIN TELEFONE T 
ON IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON IDCLIENTE = E.ID_CLIENTE 
WHERE SEXO = 'F' AND TIPO = 'CEL' AND ESTADO = 'SP';

--IFNULL
SELECT C.NOME AS CLIENTE, 
   IFNULL(C.EMAIL, 'SEM EMAIL') AS EMAIL,
   T.NUMERO AS CELULAR 

FROM CLIENTE C 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE 
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';

--FUNCOES DE AGREGACAO NUMERICAS

--MAX TRAZ O VALOR MAXIMO DE UMA COLUNA
SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

--MIN TRAZ O VALOR MINIMO DE UMA COLUNA
SELECT MIN(FEVEREIRO) AS MENOR_FEV 
FROM VENDEDORES;

--AVG TRAZ O VALOR MEDIO DE UMA COLUNA
SELECT AVG(FEVEREIRO) AS MEDIA_FEV 
FROM VENDEDORES;

--VARIAS FUNCOES
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
	   AVG (JANEIRO) AS MEDIA_JAN
FROM VENDEDORES;

--TRUNCATE remove todas as linhas de uma tabela sem registrar 
--as exclusões de linhas individuais.
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
	   TRUNCATE(AVG(JANEIRO), 2) AS MEDIA_JAN
FROM VENDEDORES;