CREATE TABLE TELEFONE(
   IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
   TIPO ENUM('COM', 'RES', 'CEL'),
   NUMERO VARCHAR(10),
   ID_CLIENTE INT,
   FOREIGN KEY(ID_CLIENTE)
   REFERENCES CLIENTE(IDCLIENTE)
);