
--VIEWS OU VISOES
--Uma View (Exibição / Visão) é uma tabela virtual (estrutura de dados) 
--baseada no conjunto de resultados de uma consulta SQL, criada a partir 
--de um conjunto de tabelas (ou outras views) presentes no banco, que 
--servem com tabelas-base.

SELECT C.NOME,  C.SEXO, 
   IFNULL(C.EMAIL, 'SEM EMAIL') AS "E-MAIL",
   T.TIpo,
   T.NUMERO,
   E.BAIRRO,
   E.CIDADE,
   E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

--CRIANDO A VIEW
CREATE VIEW RELATORIO AS 
   SELECT C.NOME, C.SEXO,
   IFNULL(C.EMAIL, 'SEM EMAIL') AS "E-MAIL",
   T.TIPO,
   T.NUMERO,
   E.BAIRRO,
   E.CIDADE,
   E.ESTADO 
FROM CLIENTE C
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;


SELECT * FROM RELATORIO;

SELECT * FROM RELATORIO
WHERE SEXO = 'F';

--DELETAR VIEW 
DROP VIEW RELATORIO;

CREATE VIEW V_RELATORIO AS 
  SELECT C.NOME, C.SEXO,
  IFNULL(C.EMAIL, 'SEM EMAIL') AS "E-MAIL",
  T.TIPO,
  T.NUMERO,
  E.BAIRRO,
  E.CIDADE,
  E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT NOME, SEXO, CIDADE
FROM V_RELATORIO;