--CRIANDO TABELA ESTOQUE
CREATE TABLE estoque (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(45) NOT NULL,
	quantidade INT NOT NULL,
	PRIMARY KEY(id)
);

--INSERINDO NOVO ITEM NA TABELA ESTOQUE
INSERT INTO estoque (descricao, quantidade) VALUES ('TV', 5);
