--CRIANDO TRIGGER QUE EXECUTA A PROCEDURE SEMPRE QUE UM NOVO ITEM E INSERIDO
DELIMITER //

CREATE TRIGGER T_LIMPA_PEDIDOS BEFORE INSERT ON estoque FOR EACH ROW 

BEGIN 

CALL limpa_pedidos()

END//

--EXECUTANDO TRIGGER
INSERT INTO ESTOQUE (DESCRICAO, QUANTIDADE) VALUES('DVD', 8);