CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

--EXIBINDO A ESTRUTURA DE UMA TABELA

--EXCLUINDO AS COLUNAS
INSERT INTO CLIENTE VALUES ('Joao', 'M', 'joaodetal@gmail.com', 988638273, '22923110', 'Garopaba - Garaopaba - Santa Catarina');
INSERT INTO CLIENTE VALUES ('Joao', 'F', 'celiadetal@gmail.com', 541521456, '47078869', 'Centro - Pato Branco - Paraná');
INSERT INTO CLIENTE VALUES ('Joao', 'M', null, 885755896, '58748895', 'Bairro Floresta - Pelotas - Rio Grande do Sul');

--COLOCANDO AS COLUNAS
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('Lilian','F','Senador Soarez - Tijuca - Rio de Janeiro - RJ','947785696',887774856);


--INSERT COMPACTO - SOMENTE MYSQL
INSERT INTO CLIENTE VALUES('Ana','F','ana@globo.com',85548962,'548556985','Pres Antonio Carlos - Centro - Sao Paulo - SP'),
                          ('Carla','F','carla@terati.com.br',7745828,'66587458','SAMUEL SILVA - Centro - Belo Horizonte - MG');



--O COMANDO SELECT
SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT ENDERECO, SEXO, EMAIL  FROM CLIENTE;

--UTILIZANDO O LIKE
SELECT NOME, SEXO FROM CLIENTE
  WHERE ENDERECO LIKE 'RJ';

--CARACTER CORINGA %
SELECT NOME, SEXO FROM CLIENTE
  WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';


--OPERADORES LOGICOS
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
  WHERE
      SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
  WHERE
      SEXO = 'M' AND ENDERECO LIKE '%RJ';


SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
  WHERE SEXO = 'F' OR ENDERECO = 'Rio de Janeiro';


--COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS
SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) AS "QUANTIDADE DE REG TAB CLIENTE" FROM CLIENTE

--UTILIZANDO O UPDATE PARA ATUALIZAR VALORES

--Altera todos colocando mesmo email
UPDATE CLIENTE SET EMAIL = 'lilian@gmail.com';

